# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BigArmaEuc <- function(pInBigMat, pOutBigMat) {
    invisible(.Call('_FractalTools_BigArmaEuc', PACKAGE = 'FractalTools', pInBigMat, pOutBigMat))
}

CPP_get_openmp_threads <- function() {
    .Call('_FractalTools_CPP_get_openmp_threads', PACKAGE = 'FractalTools')
}

CPP_set_openmp_threads <- function(n) {
    invisible(.Call('_FractalTools_CPP_set_openmp_threads', PACKAGE = 'FractalTools', n))
}

